language: csharp
dotnet: 3.1.100
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
os:
  - linux
  - osx

dist: bionic
osx_image: xcode11.2

script:
  - dotnet restore
  - dotnet test test/stashbox-hangfire/stashbox.hangfire.tests.csproj -c Release