environment:
  build_version: 3.0.0

version: $(build_version)-{build}

pull_requests:
  do_not_increment_build_number: true
  
configuration: Release

image: Visual Studio 2019

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(build_version)
  assembly_file_version: $(build_version)
  assembly_informational_version: $(build_version)

before_build:
- ps: . .\patch-version.ps1 src\stashbox-hangfire\stashbox.hangfire.csproj $($env:build_version)

build_script:
- msbuild /t:Restore stashbox.extensions.sln
- nuget restore stashbox.extensions.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% stashbox.extensions.sln
  
after_build:
- msbuild /t:Pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox-hangfire\stashbox.hangfire.csproj
- nuget pack src\stashbox-owin\stashbox.owin.csproj -Properties "Configuration=%CONFIGURATION%" -Symbols -IncludeReferencedProjects -SymbolPackageFormat snupkg -OutputDirectory artifacts
- nuget pack src\stashbox-signalr\stashbox.signalr.csproj -Properties "Configuration=%CONFIGURATION%" -Symbols -IncludeReferencedProjects -SymbolPackageFormat snupkg -OutputDirectory artifacts
- nuget pack src\stashbox-signalr-owin\stashbox.signalr.owin.csproj -Properties "Configuration=%CONFIGURATION%" -Symbols -IncludeReferencedProjects -SymbolPackageFormat snupkg -OutputDirectory artifacts
- nuget pack src\stashbox-webapi-owin\stashbox.webapi.owin.csproj -Properties "Configuration=%CONFIGURATION%" -Symbols -IncludeReferencedProjects -SymbolPackageFormat snupkg -OutputDirectory artifacts
- nuget pack src\stashbox-web-mvc\stashbox.web.mvc.csproj -Properties "Configuration=%CONFIGURATION%" -Symbols -IncludeReferencedProjects -SymbolPackageFormat snupkg -OutputDirectory artifacts
- nuget pack src\stashbox-web-webapi\stashbox.web.webapi.csproj -Properties "Configuration=%CONFIGURATION%" -Symbols -IncludeReferencedProjects -SymbolPackageFormat snupkg -OutputDirectory artifacts

test_script:
- dotnet test test\stashbox-hangfire\stashbox.hangfire.tests.csproj -c %CONFIGURATION% --no-build
- vstest.console /logger:Appveyor "test\stashbox-owin\bin\%CONFIGURATION%\Stashbox.Owin.Tests.dll" /TestAdapterPath:packages\MSTest.TestAdapter.2.1.2\build\_common\
- vstest.console /logger:Appveyor "test\stashbox-signalr\bin\%CONFIGURATION%\Stashbox.SignalR.Tests.dll" /TestAdapterPath:packages\MSTest.TestAdapter.2.1.2\build\_common\
- vstest.console /logger:Appveyor "test\stashbox-signalr-owin\bin\%CONFIGURATION%\Stashbox.AspNet.SignalR.Owin.Tests.dll" /TestAdapterPath:packages\MSTest.TestAdapter.2.1.2\build\_common\
- vstest.console /logger:Appveyor "test\stashbox-webapi-owin\bin\%CONFIGURATION%\Stashbox.AspNet.WebApi.Owin.Tests.dll" /TestAdapterPath:packages\MSTest.TestAdapter.2.1.2\build\_common\
- vstest.console /logger:Appveyor "test\stashbox-web-webapi\bin\%CONFIGURATION%\Stashbox.Web.WebApi.Tests.dll" /TestAdapterPath:packages\MSTest.TestAdapter.2.1.2\build\_common\
  
artifacts:
- path: artifacts\*.nupkg
  name: NuGet
- path: artifacts\*.snupkg
  name: NuGet Symbol Packages

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true